---

networks:
  - name: concourse
    type: manual
    subnets:
    - range: 10.244.8.0/24
      gateway: 10.244.8.1
      static: [10.244.8.2]
  - name: moviefun
    type: manual
    subnets:
    - range: 10.244.20.0/24
      gateway: 10.244.20.1
      static: [10.244.20.2]


compilation:
  cloud_properties:
    name: random
  network: moviefun
  reuse_compilation_vms: true
  workers: 6

resource_pools:

- name: concourse
  cloud_properties:
    name: random
  network: concourse
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

- name: moviefun
  cloud_properties:
    name: random
  network: concourse
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest